use_synthetic_distributions: True
use_drift: False
drift_method: linear

graph_path: ./graph.json
path_max_depth: 3
max_num_paths: 30

start_node: Thompson sampling
end_node: Albert Einstein

num_simulations: 10
num_iters: 20000
plots_path: ./plots
results_path: ./results
show_plots: False
display_ci: True

algorithms:
  #- name: thompson-sampling-[ 0, 0, 1, 1000]
  #  initial_parameters: [ 0, 0, 1, 1000]

  - name: thompson-sampling-[ 0, 0, 1, 1]
    initial_parameters: [ 0, 0, 1, 1]

  - name: ucb-2
    confidence_level: 2

  - name: epsilon-greedy-0.05
    epsilon: 0.05
