# Synthetic data configuration
use_synthetic_distributions: True # Use synthetic distribution or real distribution
synthetic_data_config:
  min_mean: 500
  max_mean: 1500
  # For a fixed std, min_std = max_std
  min_std: 30
  max_std: 30

# Drift config
use_drift: False # Use drift or not
drift_method: brownian # If use_drift, the drift method to apply (among linear and brownian)

# Graph configuration
graph_path: ./graph.json # Graph localisation if not using synthetic data
path_max_depth: 3 # Maximal paths depth for dfs algorithm
start_node: Thompson sampling # Dfs is searching for paths between start_node and end_node
end_node: Albert Einstein # Both nodes must be in the graph

max_num_paths: 100 # Maximum number of paths (for synthetic and real data)

# Simulation configuration
num_simulations: 20
num_iters: 10000
plots_path: ./plots
results_path: ./results
show_plots: False # Show plots during simulations or not (plots are saved in ./plots in all cases)
display_ci: True # Display confidence interval in aggregation plots or not

# Algorithms to run during simulation
algorithms:
  - type: unknown-mean-std-thompson-sampling
    name: NIG-TS-[ 0, 0, 1, 0.1]
    initial_parameters: [ 0, 0, 1, 0.1]
    discount_factor: 1
    window_size: null

  - type: unknown-mean-std-thompson-sampling
    name: NIG-DTS-[ 0, 0, 1, 0.1]-0.99
    initial_parameters: [ 0, 0, 1, 0.1 ]
    discount_factor: 0.99
    window_size: null

  - type: unknown-mean-thompson-sampling
    name: NORM-TS-[ 0, 900]
    initial_parameters: [ 0, 900]
    discount_factor: 1
    window_size: null

  - type: unknown-mean-thompson-sampling
    name: NORM-DTS-[ 0, 900]-0.98
    initial_parameters: [ 0, 900 ]
    discount_factor: 0.98
    window_size: null

  - type: unknown-mean-thompson-sampling
    name: NORM-SWTS-[ 0, 900]-20
    initial_parameters: [ 0, 900]
    discount_factor: 1
    window_size: 20

  - type: ucb
    name: ucb-2
    confidence_level: 2

  - type: epsilon-greedy
    name: epsilon-greedy-0.05
    epsilon: 0.05


